name: Generate Snake

on:
  # Se lance automatiquement toutes les 24h (à minuit)
  schedule:
    - cron: "0 0 * * *" 
  
  # Permet de le lancer manuellement en cliquant sur un bouton si besoin
  workflow_dispatch:
  
  # Se lance à chaque fois que tu push sur la branche main/master
  push:
    branches:
    - master
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          # Ton username GitHub
          github_user_name: aurelienfvre
          # Les fichiers qui seront générés
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - name: Push Snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
